# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ci_cd

on:
  push:
    branches: [ "ci_cd" ]
  pull_request:
    branches: [ "ci_cd" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
      - run: flutter pub get
      - run: flutter pub add riverpod
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
 
    

      
